@Vet_REST_API_HostAddress = http://localhost:5041

GET {{Vet_REST_API_HostAddress}}/api/v1/Animals/
Accept: application/json

###


GET {{Vet_REST_API_HostAddress}}/api/v1/Animals/visits/1
Accept: application/json

###


GET {{Vet_REST_API_HostAddress}}/api/v1/Animals/1
Accept: application/json

###

POST {{Vet_REST_API_HostAddress}}/api/v1/Animals/
Content-Type: application/json

{
  "name": "Kitku",
  "breed": "Caaat",
  "weight": 1.2,
  "furColour": "Grey"
}

###


PUT {{Vet_REST_API_HostAddress}}/api/v1/Animals/1
Content-Type: application/json

{
  "Name": "Test",
  "Breed": "Test",
  "Weight": 10,
  "FurColour": "Test"
}

###


DELETE {{Vet_REST_API_HostAddress}}/api/v1/Animals/1
Accept: application/json

###


GET {{Vet_REST_API_HostAddress}}/api/v1/Animals/?name=Kitku
Accept: application/json

###

POST {{Vet_REST_API_HostAddress}}/api/v1/Animals/visits/
Content-Type: application/json

  {
    "date": "2026-05-07T15:10:00",
    "animal": {
      "id": 1,
      "name": "Kitku",
      "breed": "Maine Coon",
      "weight": 5,
      "furColour": "Grey"
    },
    "description": "?",
    "price": 111.1
  }
  
###